[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"

[deploy.envVars]
DATABASE_URL = "postgresql://postgres:BdThcOYOpcqGwDmuuNLFpzmJZgbCGfvc@postgres.railway.internal:5432/railway"
